### ISSUE TITLE
Cannot build root POM

### ISSUE THREAD

**Issue by sanmai-NL** [CESNET/perun#737]
Building with ```mvn clean install``` fails due to large-scale test failure with IllegalState exceptions. It's too hard to describe the error in writing. Where can I send a surefire-reports archive?

**Comment by zlamalp** [comment]
Hi @sanmai-NL, tests require existing environment with complex setup (DB, config files etc.). If you really need to build Perun, just skip the tests. But Perun isn't something to just build, deploy and see the result. Complete configuration of all aspects and deployment is really complex issue.

**Comment by sanmai-NL** [comment]
I was testing this as a solution for identity management at [CLARIN ERIC](https://www.clarin.eu/). The name of your project came up in discussion. If there is no documentation about and/or chance of setting Perun up outside its current users, we'll have to abandon it as a solution. Please note, your website and open source development activities made me think that you are interested in popularizing Perun.

**Comment by zlamalp** [comment]
Hi @sanmai-NL,

we have internal documentation, which is not yet ready. It's usually hard if you are not common with configuration of apache, tomcat, postgres, certificates, shibboleth, kerberos etc. The future is installable dep/rpm package, but we are not there yet.

This is the reason, why we provide virtual appliance with Perun pre-installed (for academic use / organizations). If you believe you are fitting into this category, please contact our project leader (Michal Procházka / @tauceti2) in order to start cooperation with your project.

**Comment by tauceti2** [comment]
Hi Sander,

We are now mainly concentrating on deployment of Perun for several project (EGI, ELIXIR, LAS, ...). Our philosophy is to provide basic support and let users to do theirs work. Perun is quite complex tool which makes virtual organization, groups and access management easy to use for users. Services where Perun manages access control do not need to be modified, instead Perun adapt to such service. 

If you are interested we can create virtual organization in our Perun instance and you can play with it. Or we can make a video call. Let me know.

Cheers,

Michal P. (mchalp@ics.muni.cz)
